use_frameworks!

platform :ios, '8.0'

target 'DWPodTestA_Example' do
  pod 'DWPodTestA', :path => '../'

  target 'DWPodTestA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
